name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests with Vitest
        run: |
          pnpm test:coverage || echo "Vitest failed" > vitest_failed

      - name: Upload HTML Coverage Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage/index.html

